name: VentApp
options:
  bundleIdPrefix: com.jerrytheraccoon1
  deploymentTarget:
    iOS: "17.0"

settings:
  CODE_SIGN_STYLE: Manual
  CODE_SIGNING_REQUIRED: NO

targets:
  VentApp:
    type: application
    platform: iOS
    sources:
      - VentApp
    settings:
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_REQUIRED: NO
